spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:sejoung/spring-cloud-server-test.git
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            ...
            -----END RSA PRIVATE KEY-----
          ignore-local-ssh-settings: true
          default-label: develop